### PR TITLE
Update GPU constant definitions

### PR DESCRIPTION
**Pull request by pusewicz**
- Addresses https://github.com/libsdl-org/SDL/commit/73898a0a6493c43943dc675ad1eccd03e16ba0d7
- Addresses https://github.com/libsdl-org/SDL/commit/fb7245fb93fa8fd332771e020cd11fdde6556cc6
- Addresses https://github.com/libsdl-org/SDL/commit/f405def691da983a05cbd6f51114d8b9a009269d

Hat-tip to [Claude.ai](https://claude.ai/) for making this fairly automated.

@RandyGaul Please let me know if you'd like me to align the trailing `\` in `CF_PIXEL_FORMAT_DEFS` like it used to be. I opted for not doing that because editing the comments will make the alignment broken.

### CODE REVIEW

**Comment by RandyGaul** [comment]
Look like a lot of unnecessary whitespace changed snuck in

**Comment by pusewicz** [comment]
@RandyGaul I've re-aligned the whitespace as it was and force-pushed.

**Comment by RandyGaul** [comment]
Thank you for the fixes! I went with the other PR since, without whitespaces, the diff was more readable. https://github.com/RandyGaul/cute_framework/pull/211

**Comment by pusewicz** [comment]
@RandyGaul The other PR does not update the list of types of textures. My PR did that.

**Comment by RandyGaul** [comment]
Ah okay, I see. Could you sync and submit a new PR then without any whitespace differences? I know it seems nitpicky, but on my end seeing a bunch of whitespaces makes it very cumbersome to evaluate. I felt bad I wasn't able to merge yours in at the time.

**Comment by waldnercharles** [comment]
There might be a misunderstanding here. @RandyGaul, I'm not seeing many whitespace changes, but, you might be referring to the re-ordered enums. I don't actually think the re-ordering is a necessary change for things to work (Since we map between CF enums and SDL), but, I could be wrong. I think it's mostly just a nicety to keep things in sync with SDL3.

**Comment by pusewicz** [comment]
@RandyGaul I've pushed a new one here: https://github.com/RandyGaul/cute_framework/pull/213

@waldnercharles Thanks! I've opened a new PR rebased on top of current master.

**Pull request closed without merging**
