### PR TITLE
cute_framework online docs

### PR DESCRIPTION
**Pull request by chunqian**
first create RandyGaul.github.io/cute_framework github pages.

### CODE REVIEW

**Comment by RandyGaul** [comment]
From https://github.com/RandyGaul/cute_framework/issues/30

**Comment by RandyGaul** [comment]
Do I need to create RandyGaul.github.io/cute_framework before this pull request?

**Comment by chunqian** [comment]
you can pull request, then create github pages, the step[#30]

**Comment by RandyGaul** [comment]
Thanks! Will try and take a look this weekend :)

**Pull request merged**
